"""
StockSense AI — Analysis Request & Response Pydantic Schemas
"""

from typing import List, Optional, Dict, Any
from datetime import datetime, date
from pydantic import BaseModel, Field, field_validator


class AnalysisRequest(BaseModel):
    ticker: str = Field(..., min_length=1, max_length=10, example="AAPL")
    investment_amount: Optional[float] = Field(10000.0, ge=0.0, example=5000.0)
    risk_tolerance: Optional[str] = Field("moderate", example="moderate")  # conservative, moderate, aggressive
    horizons: Optional[List[str]] = Field(default_factory=lambda: ["all"], example=["all"])

    @field_validator("ticker")
    @classmethod
    def clean_ticker(cls, v: str) -> str:
        return v.strip().upper()


class BatchAnalysisRequest(BaseModel):
    tickers: List[str] = Field(..., min_items=1, max_items=20, example=["AAPL", "MSFT", "NVDA"])
    investment_amount: Optional[float] = Field(10000.0, ge=0.0)
    risk_tolerance: Optional[str] = Field("moderate")


class JobStatusResponse(BaseModel):
    job_id: str
    ticker: str
    status: str = Field(..., example="FETCHING_PRICE")  # PENDING, FETCHING_PRICE, FETCHING_FUNDAMENTALS, etc.
    step: int = Field(1, ge=1, le=14)
    total_steps: int = Field(14)
    current_step_name: str = Field("Initializing analysis")
    progress_pct: int = Field(0, ge=0, le=100)
    report_id: Optional[str] = None
    error_message: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class DataFreshnessInfo(BaseModel):
    price: Optional[datetime] = None
    fundamentals: Optional[date] = None
    news: Optional[datetime] = None
    macro: Optional[date] = None
    is_price_stale: bool = False
    is_fundamentals_stale: bool = False


class ScoreCard(BaseModel):
    score: float = Field(..., ge=0.0, le=100.0)
    status: str = Field(..., example="STRONG")
    subcomponents: Optional[Dict[str, Any]] = None
    explanation: Optional[str] = None


class HorizonPredictionResponse(BaseModel):
    horizon: str  # 7d, 30d, 3m, 6m, 1y, 3y
    current_price: float
    predicted_price: float
    expected_return_pct: float
    price_interval_10th: float
    price_interval_90th: float
    prob_positive_return: float
    confidence_score: float
    recommendation: str  # STRONG BUY, BUY, HOLD, HIGH-RISK BUY, AVOID, STRONG AVOID


class ScenarioCardResponse(BaseModel):
    name: str  # Bull, Base, Bear, Tail Risk
    price_target: float
    expected_return_pct: float
    probability: float
    investment_value: Optional[float] = None
    profit_loss: Optional[float] = None
    assumptions: Optional[List[str]] = None


class ExitPlanResponse(BaseModel):
    entry_reference: float
    hard_stop_price: float
    hard_stop_pct: float
    trailing_stop_rule: str
    profit_target_partial: float
    profit_target_full: float
    fundamental_exit_triggers: List[str]
    thesis_statement: str


class InvestmentSimulationResponse(BaseModel):
    investment_amount: float
    current_price: float
    shares: float
    suggested_position_size: float
    suggested_position_pct: float
    scenario_projections: Dict[str, Any]


class ExplainabilityResponse(BaseModel):
    reasons_for: List[str]
    reasons_against: List[str]
    key_risks: List[str]
    thesis_invalidators: List[str]
    recommendation_rationale: str


class FullReportResponse(BaseModel):
    report_id: str
    ticker: str
    company_name: str
    sector: Optional[str] = None
    market_cap: Optional[int] = None
    current_price: float
    generated_at: datetime
    data_freshness: DataFreshnessInfo
    overall_score: float
    scores: Dict[str, ScoreCard]
    recommendations: Dict[str, Any]
    veto_triggered: bool
    veto_rules_triggered: Optional[List[str]] = None
    regime_warning: Optional[str] = None
    predictions: List[HorizonPredictionResponse]
    scenarios: List[ScenarioCardResponse]
    investment_simulation: Optional[InvestmentSimulationResponse] = None
    exit_plan: Optional[ExitPlanResponse] = None
    explainability: Optional[ExplainabilityResponse] = None
    disclaimer: str = Field(
        "This report is generated by an AI-powered analytical system. It is not financial advice. "
        "Past performance of models does not guarantee future results. All investments involve risk of loss."
    )
